PowerOne/Models/AssistenteCobranca/MailModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PowerOne.Models.AssistenteCobranca
{
    public class MailModel
    {
        [Required(ErrorMessage = "{0} é obrigatório.")]
        [Display(Name = "Código")]
        public string Code { get; set; }

        [Required(ErrorMessage = "{0} é obrigatório.")]
        [Display(Name = "Descrição")]
        public string Description { get; set; }

        [Required(ErrorMessage = "{0} é obrigatório.")]
        [Display(Name = "Assunto")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "{0} é obrigatório.")]
        [Display(Name = "Mensagem")]
        public string Message { get; set; }

        [Required(ErrorMessage = "{0} é obrigatório.")]
        [Display(Name = "Tipo de Modelo")]
        public string TypeId { get; set; }

        public TypeModel Type { get; set; }

        [Display(Name ="Forma de Pagamento")]
        public string PayMethod { get; set; }
    }
}

PowerOne/Controllers/AssistenteCobranca/MailModelController.cs
using PowerOne.Models;
using PowerOne.Models.AssistenteCobranca;
using PowerOne.Models.AssistenteCobranca.ViewModel;
using PowerOne.Services.AssistenteCobranca;
using PowerOne.Util;
using System.Collections.Generic;
using System.Web.Mvc;

namespace PowerOne.Controllers.AssistenteCobranca
{
    public class MailModelController : Controller
    {

        #region atributos
        private TypeModelService _typemodelService = new TypeModelService();
        private MailModelService _mailModelService = new MailModelService();
        private BPGroupService _bPGroupService = new BPGroupService();
        #endregion
        // GET: Email
        #region index
        public ActionResult Index()
        {
            if (((Login)Session["auth"]).Autorizacoes.ModeloEmail == "N" && ((Login)Session["auth"]).Autorizacoes.Grupo.ModeloEmail == "N")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }
            List<MailModel> mailModel = new List<MailModel>();
            mailModel = _mailModelService.List();

            foreach (MailModel item in mailModel)
            {
                item.Type = _typemodelService.GetByKey(item.TypeId);
            }

            return View(mailModel);
        }
        #endregion

        #region detalhes
        public ActionResult Details(string id)
        {

            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Página não encontrada: Código de objeto não informado!" });
            }


            MailModel mailModel = _mailModelService.GetById(id);
            if (mailModel == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Código de Modelo de Email não encontrado!!" });
            }
            mailModel.Type = _typemodelService.GetByKey(mailModel.TypeId);

            return View(mailModel);
        }
        #endregion

        #region overview

        public ActionResult Overview()
        {

            List<OverviewViewModel> overviewList = new List<OverviewViewModel>();

            List<BPGroup> groups = _bPGroupService.List();

            foreach (var group in groups)
            {
                OverviewViewModel overview = new OverviewViewModel();
                overview.Group = group;

                Dictionary<string, MailModel> models = new Dictionary<string, MailModel>();
                MailModel mailModel = null;
                /*
                 * Pós-Faturamento 
                 */
                //Geral
                mailModel = _mailModelService.GetByGroupAndType(group.CodeGroup, "T0001", "G");
                models.Add("G", mailModel);
                mailModel = null;

                //Boleto
                mailModel = _mailModelService.GetByGroupAndType(group.CodeGroup, "T0001", "B");
                models.Add("B", mailModel);
                mailModel = null;

                //Transferencia
                mailModel = _mailModelService.GetByGroupAndType(group.CodeGroup, "T0001", "T");
                models.Add("T", mailModel);
                mailModel = null;

                overview.PosFaturamento = models;
                models = new Dictionary<string, MailModel>();

                /*
                 * Alerta de Vencimento
                 */
                mailModel = _mailModelService.GetByGroupAndType(group.CodeGroup, "T0002", "G");
                models.Add("G", mailModel);
                mailModel = null;

                //Boleto
                mailModel = _mailModelService.GetByGroupAndType(group.CodeGroup, "T0002", "B");
                models.Add("B", mailModel);
                mailModel = null;

                //Transferencia
                mailModel = _mailModelService.GetByGroupAndType(group.CodeGroup, "T0002", "T");
                models.Add("T", mailModel);
                mailModel = null;

                overview.AlertaVencimento = models;
                models = new Dictionary<string, MailModel>();

                /*
                 * Cobrança
                 */
                mailModel = _mailModelService.GetByGroupAndType(group.CodeGroup, "T0003", "G");
                models.Add("G", mailModel);
                mailModel = null;

                //Boleto
                mailModel = _mailModelService.GetByGroupAndType(group.CodeGroup, "T0003", "B");
                models.Add("B", mailModel);
                mailModel = null;

                //Transferencia
                mailModel = _mailModelService.GetByGroupAndType(group.CodeGroup, "T0003", "T");
                models.Add("T", mailModel);
                mailModel = null;

                overview.Cobranca = models;
                models = new Dictionary<string, MailModel>();

                overviewList.Add(overview);

            }

            return View(overviewList);

        }
        #endregion

        #region GET criar

        public ActionResult Create()
        {
            if (((Login)Session["auth"]).Autorizacoes.ModeloEmail == "N" && ((Login)Session["auth"]).Autorizacoes.Grupo.ModeloEmail == "N")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }

            List<TypeModel> typesModel = _typemodelService.List();
            ViewData["Types"] = typesModel;

            return View();


        }
        #endregion

        #region POST criar
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(MailModel model)
        {
            if (((Login)Session["auth"]).Autorizacoes.CriarModeloEmail == "N" && ((Login)Session["auth"]).Autorizacoes.Grupo.CriarModeloEmail == "N")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }

            //Verificando se existe pegando todas as categorias de modelo
            List<TypeModel> typesModel = _typemodelService.List();
            if (!ModelState.IsValid)
            {
                ViewData["Types"] = typesModel;
                return View(model);
            }

            //Verificando se existe
            if (_mailModelService.VerifyIfExist(model.Code))
            {
                string msg = "Código pertencente a um objeto já cadastrado.";
                Log.Gravar(msg, Log.TipoLog.Erro);
                ModelState.AddModelError("Code", msg);
                ViewData["Types"] = typesModel;
                return View(model);
            }

            //Verificando se nome já pertence a outro modelo
            if (_mailModelService.VerifyByName(model.Description))
            {
                string msg = "Descrição pertencente a um objeto já cadastrado.";
                Log.Gravar(msg, Log.TipoLog.Erro);
                ModelState.AddModelError("Description", msg);
                ViewData["Types"] = typesModel;
                return View(model);
            }

            string message = model.Message;

            _mailModelService.Create(model);
            TempData["Success"] = $"Modelo de Email {model.Code} cadastrado com sucesso!";

            return RedirectToAction("Index");
        }
        #endregion

        #region editar
        public ActionResult Edit(string id)
        {


            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Página não encontrada: Código de objeto não informado!" });
            }
            MailModel mailModel = _mailModelService.GetById(id);
            if (mailModel == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Código de Modelo de Email não encontrado!!" });
            }
            mailModel.Type = _typemodelService.GetByKey(mailModel.TypeId);

            if (mailModel == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Código de Modelo de Email não encontrado!!" });
            }

            List<TypeModel> typesModel = _typemodelService.List();
            ViewData["Types"] = typesModel;

            return View(mailModel);


        }
        #endregion

        [HttpPost]
        [ValidateInput(false)]

        #region editar
        public ActionResult Edit(MailModel model)
        {
            List<TypeModel> typesModel = _typemodelService.List();
            if (!ModelState.IsValid)
            {
                ViewData["Types"] = typesModel;
                return View(model);
            }

            _mailModelService.Edit(model);
            TempData["Success"] = $"Modelo de Email {model.Code} editado com sucesso!";
            return RedirectToAction("Index");
        }
        #endregion

        #region deletar
        public ActionResult Delete(string id)
        {


            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Página não encontrada: Código de objeto não informado!" });
            }

            //Verificando se o modelo está vinculado a um grupo de parceiros de negócio
            if (_mailModelService.VerifyIfIsLinkedGroup(id))
            {
                TempData["Error"] = "O Modelo de Email já está vinculado a um Grupo de Parceiros de Negócio.";
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
                return RedirectToAction("Index");
            }

            //verificando se o modelo de email já foi utilizado para disparo de emails
            if (_mailModelService.VerifyIfWasSended(id))
            {
                TempData["Error"] = "Modelo de Email já foi utilizado em envios.";
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
                return RedirectToAction("Index");
            }

            MailModel mailModel = _mailModelService.GetById(id);
            if (mailModel == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Código de Modelo de Email não encontrado!!" });
            }

PowerOne/Views/MailModel/Create.cshtml
@model PowerOne.Models.AssistenteCobranca.MailModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<PowerOne.Models.AssistenteCobranca.TypeModel> types = (List<PowerOne.Models.AssistenteCobranca.TypeModel>)ViewData["Types"];
}

<div class="row">
    <div class="card col-md-10 m-auto shadow p-3 mb-5 bg-light rounded">
        <div class="card-body">
            <h3 class="text-center">Cadastrar Modelo de Email</h3>
            <hr></hr>

            <form action="~/MailModel/Create" method="post">
                @Html.AntiForgeryToken()
                <div class="row">

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => Model.Code)
                        @Html.TextBoxFor(model => Model.Code, new { @class = "form-control" })
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => Model.TypeId)
                        @Html.DropDownListFor(model => Model.TypeId, new SelectList(types, "Code", "Name"), new { @class = "form-control" })
                    </div>

                    <div class="col-md-6">
                        @Html.LabelFor(model => Model.PayMethod)
                        <select name="PayMethod" class="form-control">
                            <option value="G">Geral</option>
                            <option value="B">Boleto</option>
                            <option value="T">Transferência Bancária</option>
                        </select>
                    </div>

                    <div class="col-md-12">
                        @Html.LabelFor(model => Model.Description)
                        @Html.TextBoxFor(model => Model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => Model.Description, String.Empty, new { @class = "text-danger" })
                    </div>

                    <div class="col-md-12">
                        @Html.ValidationMessageFor(model => Model.Code, String.Empty, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => Model.Subject)
                    @Html.TextBoxFor(model => Model.Subject, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => Model.Subject, String.Empty, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => Model.Message)
                    @Html.TextAreaFor(model => Model.Message, new { @class = "form-control editable" })
                    @Html.ValidationMessageFor(model => Model.Message, String.Empty, new { @class = "text-danger" })
                </div>
                @Html.ActionLink("arrow_back", "AssistenteCobranca", "Home", null, new { @class = "btn btn-outline-dark material-icons" })
                <button type="button" class="btn btn-outline-dark " id="myBtn" data-toggle="modal" data-target="#aviable-variables"> Variáveis Disponíveis</button>
                <button type="submit" class="btn btn-primary">Cadastrar</button>




            </form>

        </div>
    </div>
</div>


<div class="modal" id="aviable-variables">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header text-white bg-dark">
                <h4 class="modal-title">Variáveis Disponíveis</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <ul>
                    <li>%CardName% - Razão Social</li>
                    <li>%SerialNumber% - Número de Série da Nota Fiscal</li>
                    <li>%InstallmentNumber% - Número da Parcela</li>
                    <li>%DocDate% - Data de Lançamento</li>
                    <li>%DocDueDate% - Data de Vencimento</li>
                    <li>%DocTotal% - Valor Total</li>
                    <li>%DaysToDueDate% - Dias até o vencimento</li>
                    <li>%InvoiceModel% - Modelo Fiscal</li>
                </ul>
            </div>
        </div>
    </div>
</div>

PowerOne/Views/MailModel/Delete.cshtml
@model PowerOne.Models.AssistenteCobranca.MailModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Você tem certeza que deseja excluir esse Modelo de Email?</h1>

<div>
    <h3>Modelo de Email</h3>
    <hr />

    <div class="col-md-6 m-auto">
        <div class="card">
            <div class="card-header">
                <h3 class="text-center">Dados do Modelo:</h3>
            </div>
            <div class="card-body scroll max-height-300">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Code)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Code)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Subject)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Subject)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Type.Name)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Type.Name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Message)
                    </dt>

                    <dd>
                        @Html.Raw(Model.Message)
                    </dd>


                </dl>
            </div>
            <div class="card-footer">
                <form action="~/MailModel/DeleteModel" method="post">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Code)
                    <input type="submit" value="Excluir" class="btn btn-danger" />
                    @Html.ActionLink("Voltar para Lista de Modelos", "Index", "MailModel", null, new { @class = "btn btn-primary" })
                </form>
            </div>
        </div>
    </div>
</div>

PowerOne/Views/MailModel/Details.cshtml
@model PowerOne.Models.AssistenteCobranca.MailModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-center col-12">Modelo de Email</h1>
    <hr />
    <div class="col-12">
        @Html.ActionLink("arrow_back", "Index", "MailModel", null, new { @class = "btn btn-outline-primary m-3 material-icons" })
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <strong>
                    @Html.DisplayNameFor(model => model.Code):
                </strong>
            </div>
            <div class="card-body">
                @Html.DisplayFor(model => model.Code):
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <strong>
                    @Html.DisplayNameFor(model => model.Description):
                </strong>
            </div>
            <div class="card-body">
                @Html.DisplayFor(model => model.Description)
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <strong>
                    @Html.DisplayNameFor(model => model.Type.Name):
                </strong>
            </div>
            <div class="card-body">
                @Html.DisplayFor(model => model.Type.Name)
            </div>
        </div>
    </div>


    <div class="col-md-12 my-3">
        <div class="card">
            <div class="card-header">
                <strong>Mensagem:</strong>
            </div>
            <div class="card-body scroll max-height-300">
                <strong>@Html.DisplayNameFor(model => model.Subject): </strong>@Html.DisplayFor(model => model.Subject)
                <hr />

                @Html.Raw(Model.Message)
            </div>
        </div>
    </div>

</div>

PowerOne/Views/MailModel/Edit.cshtml
@model PowerOne.Models.AssistenteCobranca.MailModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<PowerOne.Models.AssistenteCobranca.TypeModel> types = (List<PowerOne.Models.AssistenteCobranca.TypeModel>)ViewData["Types"];
}



<div class="row">
    <div class="card col-md-10 m-auto shadow p-3 mb-5 bg-light rounded p-3">
        <div class="card-body">
            <h3 class="text-center">Editar Modelo de Email</h3>
            <hr></hr>

            <form action="~/MailModel/Edit" method="post">
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => Model.Code)
                        @Html.HiddenFor(model => Model.Code)
                        @Html.TextBoxFor(model => Model.Code, new { @class = "form-control", disabled = "disabled" })

                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => Model.TypeId)
                        @Html.HiddenFor(model => Model.TypeId)
                        @Html.DropDownListFor(model => Model.TypeId, new SelectList(types, "Code", "Name"), new { @class = "form-control", disabled = "disabled" })
                    </div>

                    <div class="col-md-6">
                        @Html.LabelFor(model => Model.PayMethod)
                        @Html.HiddenFor(model => Model.PayMethod)
                        <select name="PayMethod" class="form-control" disabled>
                            <option value="G">Geral</option>
                            <option value="B">Boleto</option>
                            <option value="T">Transferência Bancária</option>
                        </select>
                    </div>

                    <div class="col-md-12">
                        @Html.LabelFor(model => Model.Description)
                        @Html.TextBoxFor(model => Model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => Model.Description, String.Empty, new { @class = "text-danger" })
                    </div>

                    <div class="col-md-12">
                        @Html.ValidationMessageFor(model => Model.Code, String.Empty, new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => Model.Subject)
                        @Html.TextBoxFor(model => Model.Subject, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => Model.Subject, String.Empty, new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => Model.Message)
                    @Html.TextAreaFor(model => Model.Message, new { @class = "form-control editable" })
                    @Html.ValidationMessageFor(model => Model.Message, String.Empty, new { @class = "text-danger" })
                </div>
                @Html.ActionLink("arrow_back", "Index", "MailModel", new { @class = "btn btn-outline-dark material-icons" })


                <button type="button" class="btn btn-outline-dark" id="myBtn" data-toggle="modal" data-target="#aviable-variables">Variáveis Disponíveis</button>
                <button type="submit" class="btn btn-primary">Atualizar</button>

            </form>

        </div>
    </div>
</div>


<div class="modal" id="aviable-variables">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header text-white bg-dark">
                <h4 class="modal-title">Variáveis Disponíveis</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <ul>
                    <li>%CardName% - Razão Social</li>
                    <li>%SerialNumber% - Número de Série da Nota Fiscal</li>
                    <li>%InstallmentNumber% - Número da Parcela</li>
                    <li>%DocDate% - Data de Lançamento</li>
                    <li>%DocDueDate% - Data de Vencimento</li>
                    <li>%DocTotal% - Valor Total</li>
                    <li>%DaysToDueDate% - Dias até o vencimento</li>
                    <li>%InvoiceModel% - Modelo Fiscal</li>
                </ul>
            </div>
        </div>
    </div>
</div>

PowerOne/Views/MailModel/Index.cshtml
@model IEnumerable<PowerOne.Models.AssistenteCobranca.MailModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1 class="col-12 text-center">Modelos de E-mail</h1>
<hr />

@if (TempData["Success"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Success"].ToString()
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["Error"].ToString()
    </div>
}

<div class="card col-md-10 col-sm-12 m-auto p-0">
    <div class="card-header">
        <h3 class="text-center">Adicione Novos Modelos clicando @Html.ActionLink("aqui", "Create", "MailModel", null, new { @class = "btn btn-primary" })</h3>
    </div>
    <div class="card-body max-height-500 scroll p-0">
        <table class="table table-striped col-12">
            <thead class="thead-dark">
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Código</th>
                    <th scope="col">Descrição</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Forma de Pgto.</th>
                </tr>
            </thead>
            <tbody>
            @foreach (var model in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink("search", "Details", "MailModel", new { id = model.Code }, new { @class = "btn btn-outline-dark material-icons" })
                        @Html.ActionLink("close", "Delete", "MailModel", new { id = model.Code }, new { @class = "btn btn-outline-danger material-icons" })
                        @Html.ActionLink("edit", "Edit", "MailModel", new { id = model.Code }, new { @class = "btn btn-outline-success material-icons" })
                    </td>
                    <td>@Html.DisplayFor(modelItem => model.Code)</td>
                    <td>@Html.DisplayFor(modelItem => model.Description)</td>
                    <td>@Html.DisplayFor(modelItem => model.Type.Name)</td>
                    <td>@Html.DisplayFor(modelItem => model.PayMethod)</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

PowerOne/Views/MailModel/Overview.cshtml
@model IEnumerable <PowerOne.Models.AssistenteCobranca.ViewModel.OverviewViewModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="col-12 text-center">Visão Geral das Configurações do Sistema</h1>
<hr />

<div class="card col-md-10 col-sm-12 m-auto p-0">
    <div class="card-header">
        <h3 class="text-center">Dados gerais do sistema:</h3>
    </div>
    <div class="card-body max-height-500 scroll p-0">
        <table class="table table-striped col-12">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Grupo</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Forma de Pgto.</th>
                    <th scope="col">Modelo</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td rowspan="9">
                            @item.Group.DescGroup
                        </td>
                        <td rowspan="3">
                            Pós-Faturamento
                        </td>
                        <td>
                            Geral:
                        </td>
                        <td>
                            @(!String.IsNullOrEmpty(item.PosFaturamento["G"].Description) ? item.PosFaturamento["G"].Description : "<não configurado>")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Boleto:
                        </td>
                        <td>
                            @(!String.IsNullOrEmpty(item.PosFaturamento["B"].Description) ? item.PosFaturamento["B"].Description : "<não configurado>")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Trasferencia Bancária:
                        </td>
                        <td>
                            @(!String.IsNullOrEmpty(item.PosFaturamento["T"].Description) ? item.PosFaturamento["T"].Description : "<não configurado>")
                        </td>
                    </tr>
                    <tr>
                        <td rowspan="3">
                            Alerta de Vencimento
                        </td>
                        <td>
                            Geral:
                        </td>
                        <td>
                            @(!String.IsNullOrEmpty(item.AlertaVencimento["G"].Description) ? item.AlertaVencimento["G"].Description : "<não configurado>")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Boleto:
                        </td>
                        <td>
                            @(!String.IsNullOrEmpty(item.AlertaVencimento["B"].Description) ? item.AlertaVencimento["B"].Description : "<não configurado>")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Trasferencia Bancária:
                        </td>
                        <td>
                            @(!String.IsNullOrEmpty(item.AlertaVencimento["T"].Description) ? item.AlertaVencimento["T"].Description : "<não configurado>")
                        </td>
                    </tr>
                    <tr>
                        <td rowspan="3">
                            Cobrança
                        </td>
                        <td>
                            Geral:
                        </td>
                        <td>
                            @(!String.IsNullOrEmpty(item.Cobranca["G"].Description) ? item.Cobranca["G"].Description : "<não configurado>")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Boleto:
                        </td>
                        <td>
                            @(!String.IsNullOrEmpty(item.Cobranca["B"].Description) ? item.Cobranca["B"].Description : "<não configurado>")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Trasferencia Bancária:
                        </td>
                        <td>
                            @(!String.IsNullOrEmpty(item.Cobranca["T"].Description) ? item.Cobranca["T"].Description : "<não configurado>")
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>