PowerOne/Controllers/ConfiguracoesController.cs
using PowerOne.Models;
using PowerOne.Services;
using PowerOne.Util;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Configuration;
using System.Web;
using System.Web.Mvc;

namespace PowerOne.Controllers
{
    [Authorize]
    public class ConfiguracoesController : Controller
    {
        #region Serviços
        private ConfiguracoesService _configuracoesService = new ConfiguracoesService();
        private AutorizacoesService _autorizacoesService = new AutorizacoesService();
        #endregion

        #region Configurar Email
        public ActionResult Email()
        {
            if (((Login)Session["auth"]).Autorizacoes.Tipo != "Adm")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }

            ConfiguracoesEmail configuracoesEmail = _configuracoesService.GetConfiguracoesEmail();

            return View(configuracoesEmail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Email(ConfiguracoesEmail configEmail)
        {
            string msg = _configuracoesService.ConfigurarEmail(configEmail);

            if (msg != null)
            {
                TempData["Error"] = msg;
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
            }
            else
            {
                TempData["Success"] = "Email Configurado com Sucesso!";
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Anexo(ConfiguracoesEmail confAnexo)
        {
            string msg = _configuracoesService.ConfiguraAnexo(confAnexo);

            if (msg != null)
            {
                TempData["Error"] = msg;
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
            }
            else
            {
                TempData["Success"] = "Anexos do Email Configurados com Sucesso!";
            }

            return RedirectToAction(nameof(Email));
        }
        #endregion

        #region Temas
        public ActionResult Temas()
        {
            return View();
        }
        #endregion

        #region Configurações de Documento
        public ActionResult DocConfig()
        {
            if (((Login)Session["auth"]).Autorizacoes.Tipo != "Adm")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }

            TempData["DimensoesCtCusto"] = _configuracoesService.PegarConfiguracoesCentroCusto();

            return View();
        }
        #endregion

        #region Configurar Modelos RPT para impressao
        public ActionResult
            ConfigurarModelosImpressao(
            HttpPostedFileBase solicitacao,
            HttpPostedFileBase pedido,
            HttpPostedFileBase requerimentoEstoque,
            HttpPostedFileBase reembolso)
        {
            string msg = null;

            try
            {
                if (solicitacao != null)
                {
                    string fileName = Path.GetFileName(solicitacao.FileName);
                    string path = Path.Combine(Server.MapPath("~/Files/RPT"), fileName);

                    solicitacao.SaveAs(path);

                    msg = _configuracoesService.ConfigurarModeloImpressao("SC", "Modelo p/ Solicitação de Compras", path);
                }
                if (pedido != null)
                {
                    string fileName = Path.GetFileName(pedido.FileName);
                    string path = Path.Combine(Server.MapPath("~/Files/RPT"), fileName);

                    pedido.SaveAs(path);

                    msg = _configuracoesService.ConfigurarModeloImpressao("PC", "Modelo p/ Pedido de Compra", path);
                }
                if (requerimentoEstoque != null)
                {
                    string fileName = Path.GetFileName(requerimentoEstoque.FileName);
                    string path = Path.Combine(Server.MapPath("~/Files/RPT"), fileName);

                    requerimentoEstoque.SaveAs(path);

                    msg = _configuracoesService.ConfigurarModeloImpressao("RE", "Modelo p/ Requerimento de Estoque", path);
                }
                if (reembolso != null)
                {
                    string fileName = Path.GetFileName(reembolso.FileName);
                    string path = Path.Combine(Server.MapPath("~/Files/RPT"), fileName);

                    reembolso.SaveAs(path);

                    msg = _configuracoesService.ConfigurarModeloImpressao("RB", "Modelo p/ Reembolso", path);
                }
            }
            catch (Exception e)
            {
                msg = e.Message;
            }

            return RedirectToAction(nameof(DocConfig));
        }
        #endregion

        #region Trocar Icones
        [HttpPost]
        public ActionResult ChangeIcons(string icon)
        {                    
                if (icon != null)
                {
                    string msg = _configuracoesService.ConfigurarTema(((Models.Login)Session["auth"]).Id.ToString(), null, icon);

                    if (msg != null)
                    {
                        TempData["Error"] = msg;
                        Log.Gravar(msg, Log.TipoLog.Erro);
                    }
                    else
                    {
                        ((Models.Login)Session["auth"]).Tema = _configuracoesService.GetTema(((Models.Login)Session["auth"]).Id.ToString());
                        TempData["Success"] = "icones alterados com sucesso!";
                    }
                }
                else
                {
                    TempData["Error"] = "Selecione um icone!";
                    Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
                }

                return RedirectToAction(nameof(Temas));
        }
        #endregion

        #region Upload de Logo
        [HttpPost]
        public ActionResult UploadLogo(HttpPostedFileBase logo)
        {
            string msg = null;
            try
            {
                if (logo != null)
                {
                    string path = Path.Combine(Server.MapPath("~/Content/img"), "logo-company.png");
                    logo.SaveAs(path);
                }
            }
            catch (Exception e)
            {
                msg = e.Message;
            }

            if (msg != null)
            {
                TempData["Error"] = msg;
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
            }
            else
            {
                TempData["Success"] = "Logo do site alterada com sucesso!";
            }

            return RedirectToAction(nameof(Temas));
        }
        #endregion

        #region Configurar Cor do Menu
        [HttpPost]
        public ActionResult TrocarCorMenu(string color)
        {
            if (color != null)
            {
                string msg = _configuracoesService.ConfigurarTema(((Models.Login)Session["auth"]).Id.ToString(), color, null);

                if (msg != null)
                {
                    TempData["Error"] = msg;
                    Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
                }
                else
                {
                    ((Models.Login)Session["auth"]).Tema = _configuracoesService.GetTema(((Models.Login)Session["auth"]).Id.ToString());
                    TempData["Success"] = "Cor do menu alterado com sucesso!";
                }
            }
            else
            {
                TempData["Error"] = "Selecione uma cor!";
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
            }

            return RedirectToAction(nameof(Temas));
        }
        #endregion

        #region Configura Centros de Custo
        [HttpPost]
        public ActionResult CtCustoConfig(int[] ctCusto)
        {
            string msg = _configuracoesService.ConfigurarCentroCusto(ctCusto);

            if (msg != null)
            {
                TempData["Error"] = msg;
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
            }
            else
            {
                TempData["Success"] = "Configurações de dimensões de centro de custo alterada com sucesso!";
            }

            return RedirectToAction(nameof(DocConfig));
        }
        #endregion

        #region Autorizações
        public ActionResult Autorizacoes()
        {
            if (((Login)Session["auth"]).Autorizacoes.Tipo != "Adm")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }

            TempData["autorizacoes"] = _autorizacoesService.List();
            TempData["autorizacoesGrupo"] = _autorizacoesService.ListGrupo();

            return View();
        }

        [HttpPost]
        public ActionResult Autorizacoes(Autorizacoes autorizacoes)
        {
            string msg = _autorizacoesService.Update(autorizacoes);
            
            if (msg != null)
            {
                TempData["Error"] = msg;
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
            }
            else
            {
                TempData["Success"] = $"Autorizações de {autorizacoes.UserName} atualizadas com sucesso.";
                ((Login)Session["auth"]).Autorizacoes = _autorizacoesService.PegarAutorizacoes(((Login)Session["auth"]).Id.ToString());
                ((Login)Session["auth"]).Autorizacoes.Grupo = _autorizacoesService.PegarGrupoAutorizacoes(((Login)Session["auth"]).Autorizacoes);
            }

            return RedirectToAction(nameof(Autorizacoes));
        }
        #endregion

        #region Autorizacoes para Grupo
        public ActionResult AtualizarAutorizacoesGrupo(AutorizacoesGrupo autorizacoes)
        {
            string msg = _autorizacoesService.AtualizarAutorizacoesGrupos(autorizacoes);

PowerOne/Controllers/LoginController.cs
using System;
using System.Data;
using System.Net.Mail;
using System.Web.Mvc;
using System.Web.Security;
using Antlr.Runtime.Misc;
using Microsoft.Ajax.Utilities;
using PowerOne.Controllers.AssistenteCobranca;
using PowerOne.Models;
using PowerOne.Models.ViewModel;
using PowerOne.Services;
using PowerOne.Util;

namespace PowerOne.Controllers
{
    public class LoginController : Controller
    {

        #region Serviços(Consultas ao Banco de dados)
        private LoginService _loginService = new LoginService();
        private Email _email = new Email();
        private ConfiguracoesService _configuracoesService = new ConfiguracoesService();
        private AutorizacoesService _autorizacoesService = new AutorizacoesService();
        #endregion

        #region GET Login 
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region POST Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Login login)
        {

            if (!ModelState.IsValid)
            {
                return View(login);
            }

            string validado = isValid(login);
            if (validado == "Valid")
            {

                FormsAuthentication.SetAuthCookie(login.User, false);

                if (login.Password.ToUpper() == "NOVO")
                {
                    return RedirectToAction(nameof(AlterarSenha));
                }

                return RedirectToAction("Index", "Home");
            }
            else/* if (validado == "Invalid")*/
            {
                ModelState.AddModelError("User", "Nome de Usuário e/ou Senha incorreto(s)!");
                return View();
            }
            //else
            //{
            //    ModelState.AddModelError("User", "Você já esta logado!");
            //    return View();
            //}

        }
        #endregion

        #region Validação
        private string isValid(Login login)
        {
            Login user = _loginService.Login(login);

            if (user != null)
            {
                //bool aux = _loginService.ConsultaLogLogin(user);

                //if (aux)
                //{
                //    return "Logged";
                //}

                Tema tema = _configuracoesService.GetTema(user.Id.ToString());
                if (tema != null)
                {
                    user.Tema = tema;
                }
                else
                {
                    _configuracoesService.ConfigurarTema(user.Id.ToString(), "BLACK", "PRO");
                    user.Tema = _configuracoesService.GetTema(user.Id.ToString());
                }

                _autorizacoesService.CriarAutorizacoes(user);

                user.Autorizacoes = _autorizacoesService.PegarAutorizacoes(user.Id.ToString());
                user.Autorizacoes.Grupo = _autorizacoesService.PegarGrupoAutorizacoes(user.Autorizacoes);

                string auxiliar = _loginService.AddValorLogin(user);

                Session["auth"] = user;

                return "Valid";
            }
            else
            {
                return "Invalid";
            }
        }
        #endregion

        #region Alteração de Senha
        public ActionResult AlterarSenha()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AlterarSenha(AlterarSenhaViewModel alterarSenha)
        {
            if (!ModelState.IsValid)
            {
                return View(alterarSenha);
            }
            Login paramsLogin = new Login() { User = alterarSenha.User, Password = alterarSenha.CurrentPassword };
            Models.Login user = _loginService.Login(paramsLogin);

            if (user != null)
            {
                _loginService.EditarSenha(alterarSenha);

                Session["auth"] = user;
            }
            else
            {
                ModelState.AddModelError("CurrentPassword", "Senha atual incorreta!");
                return View(alterarSenha);
            }

            TempData["Success"] = "Senha alterada com sucesso!";
            return RedirectToAction("Logout");
        }
        #endregion

        #region Recuperar Senha
        public ActionResult RecuperarSenha()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RecuperarSenha(RecuperarSenhaViewModel recuperarSenha)
        {
            if (!ModelState.IsValid)
            {
                return View(recuperarSenha);
            }

            ConfiguracoesEmail configEmail = _configuracoesService.GetConfiguracoesEmail();
            string IdUser = _loginService.GetIdUsuarioPorNomeEmail(recuperarSenha.FirstName, recuperarSenha.LastName, recuperarSenha.Email);
            if (String.IsNullOrEmpty(IdUser))
            {
                ModelState.AddModelError("Email", "Os dados inseridos não correspondem a um usuário cadastrado!");
            }

            //editar senha
            AlterarSenhaViewModel paramsPassword = new AlterarSenhaViewModel()
            {
                Id = int.Parse(IdUser),
                //gerando senha com 10 caracteres
                NewPassword = GeradorDeSenha.GetSenha(10)
            };

            _loginService.EditarSenha(paramsPassword);
            _email.RecoverPasswordEmail(paramsPassword.NewPassword, recuperarSenha.Email, configEmail);

            TempData["Success"] = "Você recebeu um email com sua nova senha!";
            return RedirectToAction("Index");
        }
        #endregion

        #region Logout
        public ActionResult Logout()
        {
            string aux = _loginService.logoutLogLogin(((Login)Session["auth"]));
            FormsAuthentication.SignOut();
            return Redirect(nameof(Index));
        }
        #endregion
    }
}

PowerOne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="manifest" href="~/Content/manifest.json">
    <link rel="icon" type="image/png" href="~/Content/img/icon-192x192.png">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/js")
    @Scripts.Render("~/bundles/modernizr")

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    @{
        PowerOne.Models.Autorizacoes autorizacoes = ((PowerOne.Models.Login)Session["auth"]).Autorizacoes;
    }

    @if (Session["auth"] != null)
    {
        if (((PowerOne.Models.Login)Session["auth"]).Tema != null)
        {
            if (((PowerOne.Models.Login)Session["auth"]).Tema.Color != null)
            {
                <link rel="stylesheet" type="text/css" href="~/Content/var-css/@(((PowerOne.Models.Login)Session["auth"]).Tema.Color.ToString()).css">
            }
            else
            {
                <link rel="stylesheet" type="text/css" href="~/Content/var-css/BLACK.css">
            }

        }
        else
        {
            <link rel="stylesheet" type="text/css" href="~/Content/var-css/BLACK.css">
        }
    }
    else
    {
        <link rel="stylesheet" type="text/css" href="~/Content/var-css/BLACK.css">
    }


    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" type="text/css" />
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>

</head>
<body>
    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="border-right" id="sidebar-wrapper">
            <div class="sidebar-heading list-group">
                <a href="~/">
                    <img class="m-auto col-10 py-3" src="~/Content/img/logo-company.png" />
                </a>
            </div>
            <div class="list-group list-group-flush">
                <div class="accordion" id="sidebar">



                    @if (
                        (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.AssistEnvio != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.AssistEnvio != "N")
                        ||
                        (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Clientes != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.Clientes != "N")
                        ||
                        (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.ModeloEmail != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.ModeloEmail != "N")
                        ||
                        (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.CriarModeloEmail != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.CriarModeloEmail != "N")
                        ||
                        (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.GrpClientes != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.GrpClientes != "N")
                        ||
                        (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.RelatCobranças != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.RelatCobranças != "N")
                        ||
                        (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.RegistroEnvEmail != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.RegistroEnvEmail != "N")
                        )
                    {
                        @Html.ActionLink("Assistente de Cobrança", "AssistenteCobranca", "Home", null, new { @class = "list-group-item list-group-item-action" })
                    }


                    @if (
                       (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.ReqEstoque != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.ReqEstoque != "N")
                        ||
                        (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.CriarReqEstoque != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.CriarReqEstoque != "N")
                        )
                    {
                        @Html.ActionLink("Estoque", "Estoque", "Home", null, new { @class = "list-group-item list-group-item-action" })
                    }

                    @if (
                            (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.PedCompra != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.PedCompra != "N")
                            ||
                            (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.CriarPedCompra != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.CriarPedCompra != "N")
                            ||
                            (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.CriarSolCompra != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.CriarSolCompra != "N")
                            ||
                            (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.SolCompra != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.SolCompra != "N")

                        )
                    {
                        @Html.ActionLink("Compras", "Compras", "Home", null, new { @class = "list-group-item list-group-item-action" })
                    }


                    @*@Html.ActionLink("Timesheet", "Timesheet", "Home", null, new { @class = "list-group-item list-group-item-action" })*@

                    @if (
                            (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Reembolso != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.Reembolso != "N")
                            ||
                           (((PowerOne.Models.Login)Session["auth"]).Autorizacoes.CriarReembolso != "N" || ((PowerOne.Models.Login)Session["auth"]).Autorizacoes.Grupo.CriarReembolso != "N")
                        )
                    {
                        @Html.ActionLink("Financeiro", "Reembolso", "Home", null, new { @class = "list-group-item list-group-item-action" })
                    }



                    @Html.ActionLink("Configurações", "Configuracoes", "Home", null, new { @class = "list-group-item list-group-item-action" })
                    @Html.ActionLink("Sair", "Logout", "Login", null, new { @class = "list-group-item list-group-item-action" })
                </div>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="row">
                <div class="col-10">
                    <button class="btn m-3 " id="menu-toggle">
                        <span>&#9776;</span>
                    </button>
                </div>
            </div>

            <div class="container-fluid">
                @RenderBody()

            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/main.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    @*<script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>*@

    @RenderSection("scripts", required: false)


    <script>
        $(function () {
            setTimeout(function () {
                $('.alert').hide();
            }, 4000);
        });
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

        $("#checkTodos").change(function () {
            $("input:checkbox").prop('checked', $(this).prop("checked"));
        });

        $('#nav-anexos-tab').click(function () {
            $('#form_anexo').show();
            $('#form_item').hide();
        });
        $('#nav-itens-tab').click(function () {
            $('#form_anexo').hide();
            $('#form_item').show();
        });

        var editor = new MediumEditor('.editable', {
            imageDragging: false,
            toolbar: {
                buttons: [
                    'bold',
                    'italic',
                    'underline',
                    'strikethrough',
                    'anchor',
                    'orderedlist',
                    'unorderedlist',
                    'indent',
                    'outdent',
                    'justifyLeft',
                    'justifyCenter',
                    'justifyRight',
                    'justifyFull',
                    'h1',
                    'h2',
                    'h3',
                    'h4',
                    'h5',
                    'h6',
                    'removeFormat',
                    'html '
                ]
            }
        });

        function logout() {
            $.ajax({
                type: "GET",
                url: '/Login/Logout',
                success: function (msg) {
                    alert("Sua sessão expirou - Faça login novamente");
                }
            });

            //location.reload(true);
            //setTimeout(location.reload(true), 2000);
        }
        setTimeout("logout()", 3600000);

    </script>
</body>
</html>

PowerOne/Views/Shared/_LayoutLogin.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Alterar Senha</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <main class="container-fluid">
        @RenderBody()
    </main>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>