PowerOne/Models/AssistenteCobranca/BPGroup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PowerOne.Models.AssistenteCobranca
{
    public class BPGroup
    {
        [Required(ErrorMessage = "{0} é obrigatório.")]
        [Display(Name = "Código")]
        public string CodeGroup { get; set; }

        [Required(ErrorMessage = "{0} é obrigatório.")]
        [Display(Name = "Descrição")]
        public string DescGroup { get; set; }

        //[Required(ErrorMessage = "{0} é obrigatório.")]
        //[Display(Name = "Pós-Faturamento")]
        //public string DefaultModelId { get; set; }

        //[Required(ErrorMessage = "{0} é obrigatório.")]
        //[Display(Name = "Alerta de Vencimento")]
        //public string AlertModelId { get; set; }

        //[Required(ErrorMessage = "{0} é obrigatório.")]
        //[Display(Name = "Cobrança")]
        //public string BillingModelId { get; set; }
        //public MailModel DefaultModel { get; set; }

        //public MailModel AlertModel { get; set; }

        //public MailModel BillingModel { get; set; }
    }
}

PowerOne/Models/AssistenteCobranca/ViewModel/PayMethodViewModel.cs
using SAPbobsCOM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PowerOne.Models.AssistenteCobranca.ViewModel
{
    public class PayMethodViewModel
    {
        public string BPGroupId { get; set; }
        public string TypeModelId { get; set; }

        public string GeralModelId { get; set; }
        public string BankTransferModelId { get; set; }
        public string BilletModelId { get; set; }

        public List<MailModel> GeralModels { get; set; }
        public List<MailModel> BankTransferModels { get; set; }
        public List<MailModel> BilletModels { get; set; }
    }
}

PowerOne/Controllers/AssistenteCobranca/BPGroupController.cs
using PowerOne.Models;
using PowerOne.Models.AssistenteCobranca;
using PowerOne.Models.AssistenteCobranca.ViewModel;
using PowerOne.Services.AssistenteCobranca;
using PowerOne.Util;
using System.Collections.Generic;
using System.Web.Mvc;


namespace PowerOne.Controllers.AssistenteCobranca
{
    #region Grupo de Parceiro de negocios
    public class BPGroupController : Controller
    {
        #region Atributos
        private MailModelService _mailModelService = new MailModelService();
        private BPGroupService _bPGroupService = new BPGroupService();
        private GroupTypeMailService _groupTypeMailService = new GroupTypeMailService();
        #endregion

        #region Index
        public ActionResult Index()
        {
            if ( ((Login)Session["auth"]).Autorizacoes.Clientes == "N" && ((Login)Session["auth"]).Autorizacoes.Grupo.Clientes == "N")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }
            List<BPGroup> bpGroups = _bPGroupService.List();

            //Pegando os modelos de Email para Cada Grupo
            //foreach (var item in bpGroups)
            //{
            //    MailModel DefaultModel = _mailModelService.GetByGroupAndType(item.CodeGroup, "T0001",item.);
            //    MailModel AlertModel = _mailModelService.GetByGroupAndType(item.CodeGroup, "T0002");
            //    MailModel BillingModel = _mailModelService.GetByGroupAndType(item.CodeGroup, "T0003");

            //    item.DefaultModelId = DefaultModel.Code;
            //    item.DefaultModel = DefaultModel;
            //    item.AlertModelId = AlertModel.Code;
            //    item.AlertModel = AlertModel;
            //    item.BillingModelId = BillingModel.Code;
            //    item.BillingModel = BillingModel;
            //}

            return View(bpGroups);
        }
        #endregion

        #region Details
        public ActionResult Details(string code)
        {
            if (code == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Página não encontrada: Código de objeto não informado!" });
            }

            BPGroup bpGroup = GetSpecificGroup(code);

            if (bpGroup == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Página não encontrada: Código de Grupo não existe!" });
            }

            return View(bpGroup);
        }
        #endregion

        #region Create GET
        public ActionResult Create()
        {
            if (((Login)Session["auth"]).Autorizacoes.CriarGrpClientes == "N" && ((Login)Session["auth"]).Autorizacoes.Grupo.CriarGrpClientes == "N")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }
            return View();
        }
        #endregion

        #region Create POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BPGroup bpGroup)
        {
            if ( ((Login)Session["auth"]).Autorizacoes.CriarGrpClientes == "N" || ((Login)Session["auth"]).Autorizacoes.Grupo.CriarGrpClientes == "N")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }

            if (!ModelState.IsValid)
            {
                return View(bpGroup);
            }

            if (_bPGroupService.VerifyIfExist(bpGroup.CodeGroup))
            {
                string msg = "Código pertencente a um objeto já cadastrado.";
                Log.Gravar(msg, Log.TipoLog.Erro);
                ModelState.AddModelError("CodeGroup", msg);
                return View(bpGroup);
            }

            if (_bPGroupService.VerifyByName(bpGroup.DescGroup))
            {
                string msg = "Descrição pertencente a um objeto já cadastrado.";
                Log.Gravar(msg, Log.TipoLog.Erro);
                ModelState.AddModelError("DescGroup", msg);
                return View(bpGroup);
            }

            _bPGroupService.Create(bpGroup);
            TempData["Success"] = $"O grupo de Parceiros de Negócio {bpGroup.CodeGroup} foi cadastrado com sucesso!";

            return RedirectToAction("Index");
        }
        #endregion

        #region PayMethod GET
        public ActionResult PayMethod(string typeModel, string group)
        {
            PayMethodViewModel payMethodModels = new PayMethodViewModel();

            payMethodModels.BPGroupId = group;
            payMethodModels.TypeModelId = typeModel;

            //pegando a lista de modelos
            //Geral
            payMethodModels.GeralModels = _mailModelService.GetByTypepAndPayMethod(typeModel, "G");
            payMethodModels.GeralModels.Insert(0, null);
            payMethodModels.GeralModelId = _mailModelService.GetByGroupAndType(group, typeModel, "G").Code;

            //Boleto
            payMethodModels.BilletModels = _mailModelService.GetByTypepAndPayMethod(typeModel, "B");
            payMethodModels.BilletModels.Insert(0, null);
            payMethodModels.BilletModelId = _mailModelService.GetByGroupAndType(group, typeModel, "B").Code;

            //Transferencia Bancária

            payMethodModels.BankTransferModels = _mailModelService.GetByTypepAndPayMethod(typeModel, "T");
            payMethodModels.BankTransferModels.Insert(0, null);
            payMethodModels.BankTransferModelId = _mailModelService.GetByGroupAndType(group, typeModel, "T").Code;


            TempData["TypeModel"] = typeModel;
            return View(payMethodModels);
        }
        #endregion

        #region PayMethod POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PayMethod(PayMethodViewModel data)
        {
            //Geral
            if (data.GeralModelId != null)
            {
                string code = data.BPGroupId + data.GeralModelId;
                if (!_groupTypeMailService.VerifyIfExist(code))
                {
                    string codigoJaVinculado = _groupTypeMailService.GetByGroupTypePayMethod(data.BPGroupId, data.TypeModelId, "G");
                    if (codigoJaVinculado != null)
                    {
                        _groupTypeMailService.Delete(codigoJaVinculado);
                    }
                    _groupTypeMailService.Create(code, code, data.BPGroupId, data.TypeModelId, data.GeralModelId, "G");
                }
            }
            else
            {
                string codigoJaVinculado = _groupTypeMailService.GetByGroupTypePayMethod(data.BPGroupId, data.TypeModelId, "G");
                if (codigoJaVinculado != null)
                {
                    _groupTypeMailService.Delete(codigoJaVinculado);
                }
            }


            // Boleto
            if (data.BilletModelId != null)
            {
                string code = data.BPGroupId + data.BilletModelId;
                if (!_groupTypeMailService.VerifyIfExist(code))
                {
                    string codigoJaVinculado = _groupTypeMailService.GetByGroupTypePayMethod(data.BPGroupId, data.TypeModelId, "B");
                    if (codigoJaVinculado != null)
                    {
                        _groupTypeMailService.Delete(codigoJaVinculado);
                    }
                    _groupTypeMailService.Create(code, code, data.BPGroupId, data.TypeModelId, data.BilletModelId, "B");
                }
            }
            else
            {
                string codigoJaVinculado = _groupTypeMailService.GetByGroupTypePayMethod(data.BPGroupId, data.TypeModelId, "B");
                if (codigoJaVinculado != null)
                {
                    _groupTypeMailService.Delete(codigoJaVinculado);
                }
            }

            //Transferencia Bancária
            if (data.BankTransferModelId != null)
            {
                string code = data.BPGroupId + data.BankTransferModelId;
                if (!_groupTypeMailService.VerifyIfExist(code))
                {
                    string codigoJaVinculado = _groupTypeMailService.GetByGroupTypePayMethod(data.BPGroupId, data.TypeModelId, "T");
                    if (codigoJaVinculado != null)
                    {
                        _groupTypeMailService.Delete(codigoJaVinculado);
                    }
                    _groupTypeMailService.Create(code, code, data.BPGroupId, data.TypeModelId, data.BankTransferModelId, "T");
                }
            }
            else
            {
                string codigoJaVinculado = _groupTypeMailService.GetByGroupTypePayMethod(data.BPGroupId, data.TypeModelId, "T");
                if (codigoJaVinculado != null)
                {
                    _groupTypeMailService.Delete(codigoJaVinculado);
                }
            }

            TempData["Success"] = "Alteração dos modelos finalizada com sucesso!";
            return RedirectToAction(nameof(PayMethod), new { typeModel = data.TypeModelId, group = data.BPGroupId });
        }
        #endregion

        #region Edit GET
        public ActionResult Edit(string code)
        {
            if (code == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Página não encontrada: Código de objeto não informado!" });
            }

            BPGroup bpGroup = GetSpecificGroup(code);
            if (bpGroup == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Página não encontrada: Código de Grupo não existe!" });
            }

            return View(bpGroup);
        }
        #endregion

        #region Edit POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BPGroup model)
        {
            if (!ModelState.IsValid)
            {
                //Pegando dados para preencher os dropdows do formulário
                ViewData["Default"] = _mailModelService.FindByType("T0001");

PowerOne/Views/BPGroup/Create.cshtml
@model PowerOne.Models.AssistenteCobranca.BPGroup
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    List<PowerOne.Models.AssistenteCobranca.MailModel> Default = (List<PowerOne.Models.AssistenteCobranca.MailModel>)ViewData["Default"];
    List<PowerOne.Models.AssistenteCobranca.MailModel> Alert = (List<PowerOne.Models.AssistenteCobranca.MailModel>)ViewData["Alert"];
    List<PowerOne.Models.AssistenteCobranca.MailModel> Billing = (List<PowerOne.Models.AssistenteCobranca.MailModel>)ViewData["Billing"];
}

<div class="row">
    <div class="card col-md-6 m-auto shadow p-3 mb-5 bg-light rounded p-3">
        <div class="card-body">
            <h3 class="text-center">Cadastrar Grupo de Parceiros de Negócio</h3>
            <hr></hr>

            <form action="~/BPGroup/Create" method="post">
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => Model.CodeGroup)
                        @Html.TextBoxFor(model => Model.CodeGroup, new { @class = "form-control" })
                    </div>

                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => Model.DescGroup)
                        @Html.TextBoxFor(model => Model.DescGroup, new { @class = "form-control" })
                    </div>

                    <div class="col-md-12">
                        @Html.ValidationMessageFor(model => Model.CodeGroup, String.Empty, new { @class = "text-danger" })
                        @Html.ValidationMessageFor(model => Model.DescGroup, String.Empty, new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                        @Html.LabelFor(model => Model.DefaultModelId)
                        @Html.DropDownListFor(model => Model.DefaultModelId, new SelectList(Default, "Code", "Description"), new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => Model.AlertModelId)
                        @Html.DropDownListFor(model => Model.AlertModelId, new SelectList(Alert, "Code", "Description"), new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => Model.BillingModelId)
                        @Html.DropDownListFor(model => Model.BillingModelId, new SelectList(Billing, "Code", "Description"), new { @class = "form-control" })
                    </div>*@

                <button type="submit" class="btn btn-primary">Cadastrar</button>
                @Html.ActionLink("Voltar", "Index", "BPGroup", null, new { @class = "btn btn-success" })
            </form>
        </div>
    </div>
</div>

PowerOne/Views/BPGroup/Delete.cshtml
@model PowerOne.Models.AssistenteCobranca.BPGroup
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Você tem certeza que deseja excluir esse Modelo de Email?</h1>

<div>
    <h3 class="text-center">Grupo de Parceiros de Negócio</h3>
    <hr />
    <div class="col-md-6 m-auto">
        <div class="card">
            <div class="card-header">
                Dados do Modelo:
            </div>
            <div class="card-body">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.CodeGroup)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CodeGroup)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DescGroup)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.DescGroup)
                    </dd>
                </dl>

                <form action="~/BPGroup/DeleteGroup" method="post">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.CodeGroup)
                    @Html.HiddenFor(model => model.DescGroup)
                    <input type="submit" value="Excluir" class="btn btn-danger" />
                    @Html.ActionLink("Voltar para Lista de Modelos", "Index", "BPGroup", null, new { @class = "btn btn-primary" })
                </form>
            </div>
        </div>
    </div>
</div>

PowerOne/Views/BPGroup/Details.cshtml
@model PowerOne.Models.AssistenteCobranca.BPGroup
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-center col-12">Detalhes do Grupo</h1>
    <hr class="col-12" />
    <div class="col-12">
        @Html.ActionLink("Voltar", "Index", "BPGroup", null, new { @class = "btn btn-outline-primary m-3" })
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <strong>
                    @Html.DisplayNameFor(model => model.CodeGroup):
                </strong>
            </div>
            <div class="card-body">
                @Html.DisplayFor(model => model.CodeGroup):
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <strong>
                    @Html.DisplayNameFor(model => model.DescGroup):
                </strong>
            </div>
            <div class="card-body">
                @Html.DisplayFor(model => model.DescGroup):
            </div>
        </div>
    </div>

</div>

PowerOne/Views/BPGroup/Edit.cshtml
@model PowerOne.Models.AssistenteCobranca.BPGroup
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    List<PowerOne.Models.AssistenteCobranca.MailModel> Default = (List<PowerOne.Models.AssistenteCobranca.MailModel>)ViewData["Default"];
    List<PowerOne.Models.AssistenteCobranca.MailModel> Alert = (List<PowerOne.Models.AssistenteCobranca.MailModel>)ViewData["Alert"];
    List<PowerOne.Models.AssistenteCobranca.MailModel> Billing = (List<PowerOne.Models.AssistenteCobranca.MailModel>)ViewData["Billing"];
}

<div class="row">
    <div class="card col-md-7 m-auto shadow p-3 mb-5 bg-light rounded p-3">
        <div class="card-body">
            <h3 class="text-center">Editar Grupo de Parceiros de Negócio</h3>
            <hr />

            <form action="~/BPGroup/Edit" method="post">
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => Model.CodeGroup)
                        @Html.HiddenFor(model => Model.CodeGroup)
                        @Html.TextBoxFor(model => Model.CodeGroup, new { @class = "form-control", disabled = "disabled" })
                    </div>

                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => Model.DescGroup)
                        @Html.TextBoxFor(model => Model.DescGroup, new { @class = "form-control" })
                    </div>

                    <div class="col-md-12">
                        @Html.ValidationMessageFor(model => Model.CodeGroup, String.Empty, new { @class = "text-danger" })
                        @Html.ValidationMessageFor(model => Model.DescGroup, String.Empty, new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                        @Html.LabelFor(model => Model.DefaultModelId)
                        @Html.DropDownListFor(model => Model.DefaultModelId, new SelectList(Default, "Code", "Description"), new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => Model.AlertModelId)
                        @Html.DropDownListFor(model => Model.AlertModelId, new SelectList(Alert, "Code", "Description"), new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => Model.BillingModelId)
                        @Html.DropDownListFor(model => Model.BillingModelId, new SelectList(Billing, "Code", "Description"), new { @class = "form-control" })
                    </div>*@

                <button type="submit" class="btn btn-primary">Editar</button>
                @Html.ActionLink("Voltar", "Index", "BPGroup", null, new { @class = "btn btn-success" })
            </form>
        </div>
    </div>
</div>

PowerOne/Views/BPGroup/Index.cshtml
@model IEnumerable<PowerOne.Models.AssistenteCobranca.BPGroup>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="col-12 text-center">Grupo de Parceiros de Negócio</h1>
<hr />

@if (TempData["Success"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Success"].ToString()
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["Error"].ToString()
    </div>
}

<div class="card col-md-8 col-sm-12 m-auto p-0">
    <div class="card-header">
        <h3 class="text-center">Para adicionar mais grupos clique @Html.ActionLink("Aqui", "Create", "BPGroup", null, new { @class = "btn btn-primary" })</h3>
    </div>

    <div class="card-body p-0">
        <div class="scroll max-height-400">
            <table class="table table-striped col-md-12 m-auto">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Código</th>
                        <th scope="col">Descrição</th>
                        <th scope="col">Modelo de Pós-Venda</th>
                        <th scope="col">Modelo de Alerta</th>
                        <th scope="col">Modelo de Cobrança</th>
                        <th></th>
                        @*<th></th>
                            <th></th>*@
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.CodeGroup)</td>
                            <td>@Html.DisplayFor(modelItem => item.DescGroup)</td>
                            <td>@Html.ActionLink("Selecionar", "PayMethod", "BPGroup", new { typeModel = "T0001", group = item.CodeGroup }, new { @class = "btn btn-outline-primary" })</td>
                            <td>@Html.ActionLink("Selecionar", "PayMethod", "BPGroup", new { typeModel = "T0002", group = item.CodeGroup }, new { @class = "btn btn-outline-primary" })</td>
                            <td>@Html.ActionLink("Selecionar", "PayMethod", "BPGroup", new { typeModel = "T0003", group = item.CodeGroup }, new { @class = "btn btn-outline-primary" })</td>
                            @*<td>
                                    @Html.ActionLink("Detalhes", "Details", "BPGroup", new { code = item.CodeGroup }, new { @class = "btn btn-outline-dark" })
                                </td>*@
                            @*<td>
                                    @Html.ActionLink("Editar", "Edit", "BPGroup", new { code = item.CodeGroup }, new { @class = "btn btn-outline-success" })
                                </td>*@
                            <td>
                                @Html.ActionLink("close", "Delete", "BPGroup", new { code = item.CodeGroup }, new { @class = "btn btn-outline-danger material-icons"})
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

PowerOne/Views/BPGroup/PayMethod.cshtml
@model PowerOne.Models.AssistenteCobranca.ViewModel.PayMethodViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h1 class="text-center col-12">Selecionar Modelos</h1>
    <hr class="col-12" />

    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success col-md-12" role="alert">
            @TempData["Success"].ToString()
        </div>
    }

    <div class="card col-md-6 col-sm-12 m-auto p-0">
        <form action="~/BPGroup/PayMethod" method="post">
            @Html.AntiForgeryToken()
            @Html.HiddenFor(item => Model.BPGroupId)
            @Html.HiddenFor(item => Model.TypeModelId)
            <div class="card-header">
                <h3 class="col-12 text-center">

                    Modelos de
                    @if ((string)TempData["TypeModel"].ToString() == "T0001")
                    {
                        <span>Pós-Faturamento</span>
                    }
                    else if ((string)TempData["TypeModel"].ToString() == "T0002")
                    {
                        <span>Alerta de Vencimento</span>
                    }
                    else if ((string)TempData["TypeModel"].ToString() == "T0003")
                    {
                        <span>Cobranças</span>
                    }

                </h3>
            </div>
            <div class="card-body p-0">
                <div class="scroll max-height-300">
                    <table class="table table-striped col-md-12">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Forma de Pagamento</th>
                                <th scope="col">Modelo</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="font-weight-bold">Geral:</td>
                                <td>
                                    @Html.DropDownListFor(model => Model.GeralModelId, new SelectList(Model.GeralModels, "Code", "Description"), new { @class = "form-control" })
                                </td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Transferência Bancária:</td>
                                <td>
                                    @Html.DropDownListFor(model => Model.BankTransferModelId, new SelectList(Model.BankTransferModels, "Code", "Description"), new { @class = "form-control" })
                                </td>
                            </tr>
                            <tr>
                                <td class="font-weight-bold">Boleto:</td>
                                <td>
                                    @Html.DropDownListFor(model => Model.BilletModelId, new SelectList(Model.BilletModels, "Code", "Description"), new { @class = "form-control" })
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-md-6 m-auto">
                        <div class="row">
                            <button type="submit" class="btn btn-success col-md-5 m-2">Atualizar</button>
                            @Html.ActionLink("Voltar", "Index", "BPGroup", new { @class = "btn btn-outline-primary col-md-5 m-2" })
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>