PowerOne/Models/Reembolso/SolicitacaoReembolso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PowerOne.Models.Reembolso
{
    public class SolicitacaoReembolso
    {
        [Display(Name = "Nº Interno")]
        public int DocEntry { get; set; }

        [Display(Name = "Nº Documento")]
        public int DocNum { get; set; }

        [Display(Name = "SuppCatNum")]
        public int SuppCatNum { get; set; }

        [Display(Name = "Status")]
        public string DocStatus { get; set; }

        [Display(Name = "TaxDate")]
        public string TaxDate { get; set; }

        [Display(Name = "Data Documento")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DocDate { get; set; }

        [Display(Name = "Itens")]
        public List<SolicitacaoReembolsoLinhas> Itens { get; set; }

        [Display(Name = "Cód. Fornecedor")]
        public string CardCode { get; set; }

        [Display(Name = "Nome Fornecedor")]
        public string CardName { get; set; }

        [Display(Name = "VisOrder")]
        public int VisOrder { get; set; }

        [Display(Name = "Id Fornecedor")]
        public int BPL_IDAssignedToInvoice { get; set; }

        [Display(Name = "Data Necessária")]
        public float ItemCode { get; set; }

        [Display(Name = "Nome Item")]
        public string ItemName { get; set; }

        [Display(Name = "Requisitante")]
        public string Requisitante { get; set; }

        [Display(Name = "AgrNo")]
        public string AgrNo { get; set; }

        [Display(Name = "OcrCode")]
        public string OcrCode { get; set; }

        [Display(Name = "Quantidade")]
        public int Quantity { get; set; }

        [Display(Name = "LineStatus")]
        public string LineStatus { get; set; }

        [Display(Name = "Anexos")]
        public int idAnexos { get; set; }

        [Display(Name = "Filial")]
        public int Filial { get; set; }

        [Display(Name = "Comentario")]
        public string Comments { get; set; }

        [Display(Name = "TrgetEntry")]
        public int TrgetEntry { get; set; }

        [Display(Name = "Lista de Anexos")]
        public List<Arquivo> ListaAnexos { get; set; }
    }
}

PowerOne/Controllers/Reembolso/SolicitacaoReembolsoController.cs
using PowerOne.Models;
using PowerOne.Models.Enums;
using PowerOne.Models.Reembolso;
using PowerOne.Services;
using PowerOne.Services.Reembolso;
using PowerOne.Util;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace PowerOne.Controllers.Reembolso
{
    [Authorize]
    public class SolicitacaoReembolsoController : Controller
    {

        #region Serviços (Consultas ao Banco de Dados)
        SolicitacaoReembolsoService _solicitacaoReembolsoService = new SolicitacaoReembolsoService();

        ItemEstoqueService _itemEstoqueService = new ItemEstoqueService();

        ListBPService _bussinesPartner = new ListBPService();

        FiliaisService _filiaisService = new FiliaisService();

        DepositoService _depositoService = new DepositoService();

        ProjetosService _projetosService = new ProjetosService();

        CentroCustoService _centroCustoService = new CentroCustoService();

        ImpressaoService _impressaoService = new ImpressaoService();

        ConfiguracoesService _configuracoesService = new ConfiguracoesService();

        AnexosService _anexosService = new AnexosService();
        #endregion

        #region Exibir Reembolsos
        public ActionResult Index(string DataInicio, string DataFim, string Status)
        {
            if (((Login)Session["auth"]).Autorizacoes.Reembolso == "N" 
                && ((Login)Session["auth"]).Autorizacoes.Grupo.Reembolso == "N")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }

            if (String.IsNullOrEmpty(DataInicio) && String.IsNullOrEmpty(DataFim))
            {
                if (Status == null)
                {
                    Status = "T";
                }
                List<SolicitacaoReembolso> reembolsos = _solicitacaoReembolsoService.SearchList((Login)Session["auth"], null, null, Status);
                return View(reembolsos);
            }
            else
            {
                List<SolicitacaoReembolso> solicitacaos = _solicitacaoReembolsoService.SearchList((Login)Session["auth"], DataInicio, DataFim, Status);

                return View(solicitacaos);
            }
        }
        #endregion

        #region Create
        public ActionResult Create()
        {
            if (((Login)Session["auth"]).Autorizacoes.CriarReembolso == "N" 
                && ((Login)Session["auth"]).Autorizacoes.Grupo.CriarReembolso == "N")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }

            int[] dimensoesCtCusto = _configuracoesService.PegarConfiguracoesCentroCusto();

            List<ItemEstoque> itens = _itemEstoqueService.List();
            List<ListBP> bps = _bussinesPartner.List();
            List<Filiais> filiais = _filiaisService.List();
            List<Deposito> depositos = _depositoService.List(1);
            List<Projetos> projetos = _projetosService.List();

            if (dimensoesCtCusto.Contains(1))
            {
                List<CentroCusto> centroCustos = _centroCustoService.List(1);
                TempData["ctCusto"] = centroCustos;
            }

            if (dimensoesCtCusto.Contains(2))
            {
                List<CentroCusto> centroCustos2 = _centroCustoService.List(2);
                TempData["ctCusto2"] = centroCustos2;
            }
            if (dimensoesCtCusto.Contains(3))
            {
                List<CentroCusto> centroCustos3 = _centroCustoService.List(3);
                TempData["ctCusto3"] = centroCustos3;
            }
            if (dimensoesCtCusto.Contains(4))
            {
                List<CentroCusto> centroCustos4 = _centroCustoService.List(4);
                TempData["ctCusto4"] = centroCustos4;
            }
            if (dimensoesCtCusto.Contains(5))
            {
                List<CentroCusto> centroCustos5 = _centroCustoService.List(5);
                TempData["ctCusto5"] = centroCustos5;
            }

            TempData["ItensEstoque"] = itens;
            TempData["ListBP"] = bps;
            TempData["filiais"] = filiais;
            TempData["depositos"] = depositos;
            TempData["projetos"] = projetos;

            TempData["DimensoesCtCusto"] = dimensoesCtCusto;

            return View();
        }

        [HttpPost]
        public JsonResult Add(SolicitacaoReembolso reembolso)
        {
            var resultado = new { msg = "", type = "" };

            if (reembolso.Itens == null)
            {
                string errMsg = "O Reembolso deve ter pelo menos um item!";
                Log.Gravar(errMsg, Log.TipoLog.Erro);
                resultado = new
                {
                    msg = errMsg,
                    type = "error"
                };

                return Json(resultado, JsonRequestBehavior.AllowGet);
            }

            string msg = _solicitacaoReembolsoService.Create(reembolso, (Login)Session["auth"]);

            if (msg != null)
            {
                resultado = new
                {
                    msg = msg,
                    type = "error"
                };
            }
            else
            {
                resultado = new
                {
                    msg = "Documento adicionado com sucesso!",
                    type = "success"
                };
            }

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Aprovar Reembolso
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Anexo(string observacoes, int DocEntry)
        {

            bool confirmaReembolso = _solicitacaoReembolsoService.AddAnexo(observacoes, DocEntry, (Login)Session["auth"]);
            if (confirmaReembolso == true)
            {
                TempData["Success"] = "O Reembolso foi aprovado!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = "Ocorreu uma falha no processo";
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region Detalhes do Reembolso
        public ActionResult Details(int DocEntry)
        {
            if (((Login)Session["auth"]).Autorizacoes.Reembolso == "N" 
                && ((Login)Session["auth"]).Autorizacoes.Grupo.Reembolso == "N")
            {
                return RedirectToAction("NaoAutorizado", "Home");
            }

            int[] dimensoesCtCusto = _configuracoesService.PegarConfiguracoesCentroCusto();

            if (dimensoesCtCusto.Contains(1))
            {
                List<CentroCusto> centroCustos = _centroCustoService.List(1);
                TempData["ctCusto"] = centroCustos;
            }

            if (dimensoesCtCusto.Contains(2))
            {
                List<CentroCusto> centroCustos2 = _centroCustoService.List(2);
                TempData["ctCusto2"] = centroCustos2;
            }
            if (dimensoesCtCusto.Contains(3))
            {
                List<CentroCusto> centroCustos3 = _centroCustoService.List(3);
                TempData["ctCusto3"] = centroCustos3;
            }
            if (dimensoesCtCusto.Contains(4))
            {
                List<CentroCusto> centroCustos4 = _centroCustoService.List(4);
                TempData["ctCusto4"] = centroCustos4;
            }
            if (dimensoesCtCusto.Contains(5))
            {
                List<CentroCusto> centroCustos5 = _centroCustoService.List(5);
                TempData["ctCusto5"] = centroCustos5;
            }

            SolicitacaoReembolso solicitacaoReembolso = _solicitacaoReembolsoService.GetByKey(DocEntry);
            solicitacaoReembolso.ListaAnexos = _anexosService.GetAnexo(DocEntry, TipoDocumento.Reembolso);

            return View(solicitacaoReembolso);
        }
        #endregion

        #region Fechar Status do Reembolso
        public ActionResult FecharStatus(int DocEntry)
        {
            string msg = _solicitacaoReembolsoService.FecharStatus(DocEntry);

            if (msg != null)
            {
                TempData["Error"] = msg;
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
            }
            else
            {
                TempData["Success"] = "Status do Documento Alterado com sucesso!";
            }

            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Deletar Linhas Reembolso
        public ActionResult DeleteLinha(int id, int line)
        {
            return RedirectToAction("Details", new { DocEntry = id });

            //return RedirectToAction("Details", new { DocEntry = id });
        }
        #endregion

        #region Imprimir Pedido de Compra
        public ActionResult Imprimir(int DocEntry)
        {
            string path = _configuracoesService.GetDiretorioModeloImpressao("RB");

            if (!System.IO.File.Exists(path))
            {
                TempData["Error"] = "Arquivo não existente! Configure o Modelo de Impressão novamente!";
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
                return RedirectToAction(nameof(Index));
            }

            if (path != null)
            {
                string file = _impressaoService.Imprimir(DocEntry, path, TipoDocumento.Reembolso);
                string content_type = "application/pdf";
                string nameFile = $"REEMBOLSO_{DocEntry}.pdf";


                return File(file, content_type, nameFile);
            }
            else
            {
                TempData["Error"] = "Modelo Crystal Reports não configurado, acesse as configurações de documentos.";
                Log.Gravar((string)TempData["Error"], Log.TipoLog.Erro);
                return RedirectToAction(nameof(Index));
            }

PowerOne/Views/SolicitacaoReembolso/Details.cshtml
@model PowerOne.Models.Reembolso.SolicitacaoReembolso
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="col-12 text-center">Detalhes do Reembolso</h1>
<hr />

@if (TempData["Success"] != null)
{

    <div class="alert alert-success" role="alert">
        @TempData["Success"].ToString()
    </div>
}
else if (TempData["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["Error"].ToString()
    </div>
}

<div class="card col-10 mx-auto bg-light p-0">

    @*@Html.AntiForgeryToken()
    @Html.HiddenFor(id => Model.DocEntry)*@
    <div class="card-header p-4">
        <div class="row">
            <div class="col-md-6">
                <div class="row py-2">
                    <strong class="col-md-6">@Html.DisplayNameFor(model => Model.DocNum):</strong>
                    <div class="col-md-6">
                        <input class="form-control" value="@Html.DisplayFor(model => Model.DocNum)" readonly />
                    </div>
                </div>
                <div class="row py-2">
                    <strong class="col-md-6">@Html.DisplayNameFor(model => Model.CardCode):</strong>
                    <div class="col-md-6">
                        <input class="form-control" value="@Html.DisplayFor(model => Model.CardCode)" readonly />
                    </div>
                </div>
                <div class="row py-2">
                    <strong class="col-md-6">@Html.DisplayNameFor(model => Model.CardName):</strong>
                    <div class="col-md-6">
                        <input class="form-control" value="@Html.DisplayFor(model => Model.CardName)" readonly />
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row py-2">
                    <strong class="col-md-6">@Html.DisplayNameFor(model => Model.DocDate):</strong>
                    <div class="col-md-6">
                        <input class="form-control" value="@Html.DisplayFor(model => Model.DocDate)" readonly />
                    </div>
                </div>
                <div class="row py-2">
                    <strong class="col-md-6">Classificação do Documento:</strong>
                    <div class="col-md-6">
                        <input class="form-control" value="Reembolso" readonly />
                    </div>
                </div>
                <div class="row py-2">
                    <strong class="col-md-6">@Html.DisplayNameFor(model => Model.DocStatus):</strong>
                    <div class="col-md-6">
                        @if (Model.DocStatus == "O")
                        {
                            <input type="text" class="form-control from-group" value="Aberto" readonly />
                        }
                        else
                        {
                            <input type="text" class="form-control from-group" value="Fechado" readonly />
                        }
                    </div>
                </div>
            </div>
        </div>
        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-link active" id="nav-itens-tab" data-toggle="tab" href="#nav-itens" role="tab" aria-controls="nav-itens" aria-selected="true">Itens</a>
                <a class="nav-link" id="nav-anexos-tab" data-toggle="tab" href="#nav-anexos" role="tab" aria-controls="nav-anexos" aria-selected="false">Anexos</a>
            </div>
        </nav>
    </div>
    <div class="card-body p-0 scroll max-height-250">
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active card-body p-0 scroll max-height-500" id="nav-itens" role="tabpanel" aria-labelledby="nav-itens-tab">
                @if (Model == null)
                {
                    <h2 class="text-center"> Não Foram encontrados itens nessa Requisição de Estoque</h2>
                }
                else
                {
                    <table class="table table-striped col-md-12 m-auto">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Dt. Lançamento</th>
                                <th scope="col">Código Item</th>
                                <th scope="col">Descrição</th>
                                <th scope="col">Quantidade</th>

                                @if (TempData["ctCusto"] != null)
                                {
                                    <th scope="col" class="th-ctCusto">Centro de custo</th>
                                }
                                @if (TempData["ctCusto2"] != null)
                                {
                                    <th scope="col" class="th-ctCusto">Centro de custo 2</th>
                                }
                                @if (TempData["ctCusto3"] != null)
                                {
                                    <th scope="col" class="th-ctCusto">Centro de custo 3</th>
                                }
                                @if (TempData["ctCusto4"] != null)
                                {
                                    <th scope="col" class="th-ctCusto">Centro de custo 4</th>
                                }
                                @if (TempData["ctCusto5"] != null)
                                {
                                    <th scope="col" class="th-ctCusto">Centro de custo 5</th>
                                }

                                <th scope="col">Contrato</th>
                                <th scope="col">Projeto</th>
                                <th scope="col">Texto Livre</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Itens)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(model => item.DocDate)</td>
                                    <td>@Html.DisplayFor(model => item.ItemCode)</td>
                                    <td>@Html.DisplayFor(model => item.ItemName)</td>
                                    <td>@Html.DisplayFor(model => item.Quantity)</td>

                                    @if (TempData["ctCusto"] != null)
                                    {
                                        <td>@Html.DisplayFor(model => item.OcrName)</td>
                                    }
                                    @if (TempData["ctCusto2"] != null)
                                    {
                                        <td>@Html.DisplayFor(model => item.OcrName2)</td>
                                    }
                                    @if (TempData["ctCusto3"] != null)
                                    {
                                        <td>@Html.DisplayFor(model => item.OcrName3)</td>
                                    }
                                    @if (TempData["ctCusto4"] != null)
                                    {
                                        <td>@Html.DisplayFor(model => item.OcrName4)</td>
                                    }
                                    @if (TempData["ctCusto5"] != null)
                                    {
                                        <td>@Html.DisplayFor(model => item.OcrName5)</td>
                                    }

                                    @*<td>@Html.DisplayFor(model => item.OcrName2)</td>
                                        <td>@Html.DisplayFor(model => item.OcrName3)</td>
                                        <td>@Html.DisplayFor(model => item.OcrName4)</td>
                                        <td>@Html.DisplayFor(model => item.OcrName5)</td>*@

                                    <td>@Html.DisplayFor(model => item.Contrato)</td>
                                    <td>@Html.DisplayFor(model => item.Projeto)</td>
                                    <td>@Html.DisplayFor(model => item.FreeTxt)</td>

                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
            <div class="tab-pane fade show p-0 scroll max-height-500" id="nav-anexos" role="tabpanel" aria-labelledby="nav-anexos-tab">
                <table class="table table-striped col-md-12 m-auto">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Nome</th>
                            <th scope="col">Extensão</th>
                            <th scope="col">Diretório</th>
                        </tr>
                    </thead>
                    <tbody id="anexos">
                        @foreach (PowerOne.Models.Arquivo anexo in Model.ListaAnexos)
                        {
                            <tr>
                                <td>@Html.DisplayFor(m => anexo.Nome)</td>
                                <td>@Html.DisplayFor(m => anexo.Extensao)</td>
                                <td>@Html.DisplayFor(m => anexo.Diretorio)</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="card-footer ">
        <div class="row">
            <form action="~/SolicitacaoReembolso/EditarAnexo" method="post" enctype="multipart/form-data" id="form_anexo" style="display:none" class="col-md-5 mx-auto">
                <div class="form-group">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(docEntry => Model.DocEntry, new { Name = "DocEntry" })
                    @Html.HiddenFor(docEntry => Model.idAnexos, new { Name = "idAnexos" })
                    <label>Anexo:</label>
                    <div class="row">
                        <input type="file" id="input_anexo" class="form-control col-10 h-100" name="file">
                        <div class="col-2">
                            <button type="submit" class="btn btn-success Small">
                                <i class="material-icons">file_upload</i>
                            </button>
                        </div>

                    </div>
                </div>
            </form>
        </div>
        <div class="row">
            <div class="col-md-6 text-center m-auto">
                <label>Observações do Reembolso:</label>
                <textarea class="form-control" readonly style="resize:none" id="obs" name="obs">@Html.DisplayFor(model => Model.Comments)</textarea>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col">
                @if (Model.DocStatus == "O")
                {
                    <button type="button" class="btn btn-danger btn-block" data-toggle="modal" data-target="#confirmar">
                        Fechar Documento
                    </button>
                }
                else
                {
                    <button class="btn btn-danger form-control btn-block" disabled>Fechar Documento</button>
                }
            </div>
            <div class="col">
                @if (Model.DocStatus == "O")
                {
                    @Html.ActionLink("Adicionar Anexo", "Adicionar Anexo", "SolicitacaoReembolso", new { @class = "btn btn-success form-control btn-block" })
                }
                else
                {
                    <button class="btn btn-success form-control btn-block" disabled>Adicionar Anexo</button>
                }
            </div>
            <div class="col">
                @Html.ActionLink("Voltar", "Index", "SolicitacaoReembolso", new { @class = "btn btn-outline-primary form-control btn-block" })
            </div>

        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="confirmar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja mesmo fechar o documento? essa ação altera o status do documento de Aberto para Fechado
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Não, Voltar</button>
                @Html.ActionLink("Sim, Desejo fechar o Documento", "FecharStatus", "SolicitacaoReembolso", new { DocEntry = Model.DocEntry }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

PowerOne/Views/SolicitacaoReembolso/Index.cshtml
@model IEnumerable<PowerOne.Models.Reembolso.SolicitacaoReembolso>
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h1 class="col-12 text-center">Lista das Solicitações de Reembolso</h1>
<hr />

@if (TempData["Success"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Success"].ToString()
    </div>
}
else if (TempData["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["Error"].ToString()
    </div>
}

<div class="card col-10 mx-auto bg-light p-0">
    <div class="card-header">
        <form action="~/SolicitacaoReembolso/Index" method="get">

            <div class="row">
                <div class="col-md-3 form-group col-sm-12">
                    <label>Data de Lançamento:</label>
                    <input type="date" name="DataInicio" class="form-control" />
                </div>
                <div class="col-md-3 form-group col-sm-12">
                    <label>Até:</label>
                    <input type="date" name="DataFim" class="form-control" />
                </div>
                <div class="col-md-3 form-group col-sm-12">
                    <label>Status:</label>
                    <select name="Status" class="form-control">
                        <option value="T">Todas</option>
                        <option value="O">Aberta</option>
                        <option value="C">Fechada</option>
                    </select>
                </div>
                <div class="col-md-3 form-group col-sm-12">
                    <div class="row">
                        <label class="col-12"><br /></label>
                        <button type="submit" class="btn btn-outline-success col-md-12"><i class="material-icons">search</i></button>
                    </div>

                </div>
            </div>
        </form>
    </div>
    <div class="card-body p-0 scroll max-height-500">
        <table class="table table-striped col-md-12 m-auto text-center">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Visualizar</th>
                    <th scope="col">Imprimir</th>
                    <th scope="col">Fechar</th>

                    @*<th scope="col">Número interno do Documento</th>*@
                    <th scope="col">Número do Documento</th>
                    <th scope="col">Status do Documento</th>
                    <th scope="col">Data do Documento</th>
                    @*<th scope="col">Data de entrega</th>*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@Html.ActionLink("arrow_forward", "Details", "SolicitacaoReembolso", new { DocEntry = item.DocEntry }, new { @class = "btn btn-outline-dark material-icons" })</td>
                    <td>
                        @Html.ActionLink("print", "Imprimir", "SolicitacaoReembolso", new { DocEntry = item.DocEntry }, new { @class = "btn btn-outline-primary material-icons" })
                    </td>

                    @if (item.DocStatus == "Fechada")
                    {
                        <td><button type="button" class="btn btn-outline-danger material-icons" disabled>close</button></td>
                    }
                    else
                    {
                        <td>@Html.ActionLink("close", "FecharStatus", "SolicitacaoReembolso", new { DocEntry = item.DocEntry }, new { @class = "btn btn-outline-danger material-icons" })</td>
                    }
                    @*<td>@Html.DisplayFor(model => item.DocEntry)</td>*@
                    <td>@Html.DisplayFor(model => item.DocNum)</td>
                    <td>@Html.DisplayFor(model => item.DocStatus)</td>
                    <td>@Html.DisplayFor(model => item.DocDate)</td>
                    @*<td>@Html.DisplayFor(model => item.TaxDate)</td>*@
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>